server:
  port: 8080
spring:
  application:
    name: spring-boot-prometheus
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: ALWAYS
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}