server:
  port: 8080
spring:
  application:
    name: spring-boot-aligenie
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    cache: false
  mvc:
    throw-exception-if-no-handler-found: true